apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  namespace: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydeploy
  template:
    metadata:
      labels:
        app: mydeploy
        web: apache
    spec:
      containers:
      - name: mydeploy
        image: httpd:alpine

